name: Python Publish

on:
  release:
    types: [created]

permissions:
  contents: read
  pull-requests: read # to detect changes files

jobs:
  pypi:
    name: Pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      - name: Build
        run: |
          uv build
      - name: Publish
        run: |
          uv publish --token ${{ secrets.PYPI_TOKEN }}
