name: Build

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  packages: write
  contents: read
  pull-requests: read # to detect changes files

jobs:
  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - name: Python Install and Test
        uses: descope/.github/.github/actions/python/poetry/setup@main
